name: Update Image List
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update image_list.json
        id: latest
        run: "curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.PACKAGE_LIST_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/orgs/ublue-os/packages?package_type=container&page=1&per_page=100' > /tmp/image_list1.json"
        run: "curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.PACKAGE_LIST_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/orgs/ublue-os/packages?package_type=container&page=2&per_page=100' > /tmp/image_list2.json"
        run: "curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.PACKAGE_LIST_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/orgs/ublue-os/packages?package_type=container&page=3&per_page=100' > /tmp/image_list3.json"
        run: "jq -s 'reduce .[] as $item ({}; . * $item)' /tmp/image_list*.json > image_list.json"

      - name: Write image_list.json to Repostiory
        uses: test-room-7/action-update-file@v1
        with:
            file-path: image_list.json
            commit-msg: Image List Update
            github-token: ${{ secrets.GITHUB_TOKEN }}
